//Source Video
export const ADD_SOURCE_VIDEO_PATH = "ADD_SOURCE_VIDEO_PATH";
export const INCREMENT_INDEX = "INCREMENT_INDEX";
export const RESET_INDEX = "RESET_INDEX";
export const RESET_SOURCE_VIDEO = "RESET_SOURCE_VIDEO";

//Parts
export const ADD_PART = "ADD_PART";
export const REMOVE_PART = "REMOVE_PART";

//Transition Video
export const UPDATE_TRANSITION_VIDEO_PATH = "UPDATE_TRANSITION_VIDEO_PATH";

//Result Video
export const UPDATE_RESULT_VIDEO_PATH = "UPDATE_RESULT_VIDEO_PATH";
export const ADD_RESULT_ID = "ADD_RESULT_ID";
export const REMOVE_RESULT_ID = "REMOVE_RESULT_ID";

